### ISSUE TITLE
New release for Mac OS X, please?

### ISSUE THREAD

**Issue by Clemens-H** [modula3/cm3#13] opened 2016-05-20 18:04 UTC
Hi, first, thanks for the great work!  I installed the latest release for Mac OS X (d5.10.0) and tried to compile a simple program.

Unfortunately, there are a few problems (assuming I use cm3 correctly).

First, I had to remove "& SL" in cm3.cfg, see below.

Second, cm3 fails to find .M3EXPORTS because of a missing slash between bin and .. in the path, see below.

Would you please make a new release for Mac OS X?

Cheers,
Clemens
# 

$ cat Main.m3
MODULE Main;

IMPORT IO;

VAR name: TEXT;

BEGIN
  IO.Put("Enter your name: ");
  name := IO.GetLine();
  IO.Put("Hello " & name & "!\n");
END Main.
# 

$ ~/src/cm3-installed/bin/cm3
--- building in AMD64_DARWIN ---

quake runtime error: "/Users/Clemens/src/cm3-installed/bin/cm3.cfg", line 2: quake runtime error: undefined variable: SL

--procedure--  -line-  -file---
                    2  /Users/Clemens/src/cm3-installed/bin/cm3.cfg
new source -> compiling Main.m3
"../Main.m3", line 9: warning: potentially unhandled exception: IO.Error
1 warning encountered
Main.ms:1:9: error: unsupported directive '.stabs'
        .stabs  "/Users/Clemens/Languages/Modula3/Hello/AMD64_DARWIN/",100,0,0,Ltext0
                ^
Main.ms:2:9: error: unsupported directive '.stabs'
        .stabs  "Main.mc",100,0,0,Ltext0
                ^
Main.ms:5:9: error: unsupported directive '.stabs'
        .stabs  "gcc2_compiled.",60,0,0,0
                ^
Main.ms:6:9: error: unsupported directive '.stabs'
        .stabs  "procedures_have_extra_block.",60,0,0,0
                ^
Main.ms:7:9: error: unsupported directive '.stabs'
        .stabs  "m3_widechar_bitsize_16.",60,0,0,0
                ^
Main.ms:11:2: error: unknown directive
        .stabd  46,0,0
        ^
Main.ms:12:9: error: unsupported directive '.stabs'
        .stabs  "../Main.m3",132,0,0,Ltext1
                ^
Main.ms:14:2: error: unknown directive
        .stabd  68,0,7
        ^
Main.ms:24:2: error: unknown directive
        .stabd  68,0,7
        ^
Main.ms:29:2: error: unknown directive
        .stabd  68,0,8
        ^
Main.ms:33:2: error: unknown directive
        .stabd  68,0,9
        ^
Main.ms:41:2: error: unknown directive
        .stabd  68,0,10
        ^
Main.ms:84:9: error: unsupported directive '.stabs'
        .stabs  "Main_M3:F(0,1)=*(0,2)=(0,2)",36,0,7,_Main_M3
                ^
Main.ms:85:9: error: unsupported directive '.stabs'
        .stabs  "mode:p(0,3)=@s64;r(0,3);01000000000000000000000;0777777777777777777777;",160,0,0,-40
                ^
Main.ms:86:2: error: unknown directive
        .stabn  192,0,0,LFBB1
        ^
Main.ms:87:2: error: unknown directive
        .stabn  192,0,0,LBB2
        ^
Main.ms:88:2: error: unknown directive
        .stabn  224,0,0,LBE2
        ^
Main.ms:89:2: error: unknown directive
        .stabn  224,0,0,Lscope1
        ^
Main.ms:91:9: error: unsupported directive '.stabs'
        .stabs  "",36,0,0,Lscope1-LFBB1
                ^
Main.ms:92:2: error: unknown directive
        .stabd  78,0,0
        ^
Main.ms:149:9: error: unsupported directive '.stabs'
        .stabs  "L_1:S(0,4)=s200;",38,0,0,_L_1
                ^
Main.ms:150:9: error: unsupported directive '.stabs'
        .stabs  "MM_Main:S(0,5)=s184;",38,0,0,_MM_Main
                ^
Main.ms:201:9: error: unsupported directive '.stabs'
        .stabs  "",100,0,0,Letext0
                ^
  assemble => 1
assembler failed assembling: Main.ms
compilation failed => not building program "prog"
Fatal Error: package build failed
# 

$ ~/src/cm3-installed/bin/cm3 Main.m3
--- building in AMD64_DARWIN ---

"/Users/Clemens/Languages/Modula3/Hello/AMD64_DARWIN/m3make.args", line 5: quake runtime error: unable to open "/Users/Clemens/src/cm3-installed/bin../pkg/libm3/AMD64_DARWIN/.M3EXPORTS" for reading

--procedure--  -line-  -file---
import             --  <builtin>
                    5  /Users/Clemens/Languages/Modula3/Hello/AMD64_DARWIN/m3make.args

Fatal Error: package build failed

**Comment by darko20** [comment] 2016-05-20 18:07
You need to install GCC 4.9 in order to have the right tools installed.

**Comment by Clemens-H** [comment] 2016-05-20 18:11
I have this in my path:

$ gcc --version
gcc (MacPorts gcc49 4.9.3_0) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by darko20** [comment] 2016-05-20 18:16
Can you have a look in your CM3 config file and see what gcc it's
referencing? Also what version of MacOS are you running?

**Comment by Clemens-H** [comment] 2016-05-20 19:16
I run the latest Mac OS X, 10.11.5.

I removed the SL directory in bin/cm3.cfg like this.  Now I see why I was missing the slash, I assume it was at the end of SL which is not defined for me.

==========

$ cat cm3.cfg

INSTALL_ROOT = (path() & "..")

include(path() & "/config/AMD64_DARWIN")

**Comment by Clemens-H** [comment] 2016-05-20 19:18
Now if I change my cm3.cfg like this, it works better, but I get a new error.

=========
$ cat cm3.cfg

INSTALL_ROOT = (path() & "/..")

include(path() & "/config/AMD64_DARWIN")
==========
$ ~/src/cm3-installed/bin/cm3 
--- building in AMD64_DARWIN ---

new source -> compiling Main.m3
"../Main.m3", line 9: warning: potentially unhandled exception: IO.Error
1 warning encountered
Main.ms:1:9: error: unsupported directive '.stabs'
        .stabs  "/Users/Clemens/Languages/Modula3/Hello/AMD64_DARWIN/",100,0,0,Ltext0
                ^
Main.ms:2:9: error: unsupported directive '.stabs'
        .stabs  "Main.mc",100,0,0,Ltext0
                ^
Main.ms:5:9: error: unsupported directive '.stabs'
        .stabs  "gcc2_compiled.",60,0,0,0
                ^
Main.ms:6:9: error: unsupported directive '.stabs'
        .stabs  "procedures_have_extra_block.",60,0,0,0
                ^
Main.ms:7:9: error: unsupported directive '.stabs'
        .stabs  "m3_widechar_bitsize_16.",60,0,0,0
                ^
Main.ms:11:2: error: unknown directive
        .stabd  46,0,0
        ^
Main.ms:12:9: error: unsupported directive '.stabs'
        .stabs  "../Main.m3",132,0,0,Ltext1
                ^
Main.ms:14:2: error: unknown directive
        .stabd  68,0,7
        ^
Main.ms:24:2: error: unknown directive
        .stabd  68,0,7
        ^
Main.ms:29:2: error: unknown directive
        .stabd  68,0,8
        ^
Main.ms:33:2: error: unknown directive
        .stabd  68,0,9
        ^
Main.ms:41:2: error: unknown directive
        .stabd  68,0,10
        ^
Main.ms:84:9: error: unsupported directive '.stabs'
        .stabs  "Main_M3:F(0,1)=*(0,2)=(0,2)",36,0,7,_Main_M3
                ^
Main.ms:85:9: error: unsupported directive '.stabs'
        .stabs  "mode:p(0,3)=@s64;r(0,3);01000000000000000000000;0777777777777777777777;",160,0,0,-40
                ^
Main.ms:86:2: error: unknown directive
        .stabn  192,0,0,LFBB1
        ^
Main.ms:87:2: error: unknown directive
        .stabn  192,0,0,LBB2
        ^
Main.ms:88:2: error: unknown directive
        .stabn  224,0,0,LBE2
        ^
Main.ms:89:2: error: unknown directive
        .stabn  224,0,0,Lscope1
        ^
Main.ms:91:9: error: unsupported directive '.stabs'
        .stabs  "",36,0,0,Lscope1-LFBB1
                ^
Main.ms:92:2: error: unknown directive
        .stabd  78,0,0
        ^
Main.ms:149:9: error: unsupported directive '.stabs'
        .stabs  "L_1:S(0,4)=s200;",38,0,0,_L_1
                ^
Main.ms:150:9: error: unsupported directive '.stabs'
        .stabs  "MM_Main:S(0,5)=s184;",38,0,0,_MM_Main
                ^
Main.ms:201:9: error: unsupported directive '.stabs'
        .stabs  "",100,0,0,Letext0
                ^
  assemble => 1
assembler failed assembling: Main.ms
compilation failed => not building program "prog"
Fatal Error: package build failed

**Comment by darko20** [comment] 2016-05-20 19:44
The problem is that you're using the Apple GCC compiler. When I said GCC
4.9 I actually meant the vanilla one installed by something like MacPorts,
not the one that Apple has hacked for their own purposes. You'll have to
install it yourself.

You have to make sure that the correct GCC is being called and you can
check that in /usr/local/cm3/bin/config/AMD64_DARWIN (or wherever you've
installed the compiler). Mine is as follows:

% Copyright 1996-2000 Critical Mass, Inc. All rights reserved.
% See file COPYRIGHT-CMASS for details.
%

readonly SYSTEM_CC = "/opt/local/bin/gcc"
readonly SYSTEM_LIBTOOL = "/opt/local/bin/libtool"
readonly SYSTEM_ASM = "/opt/local/bin/as"


readonly TARGET = "AMD64_DARWIN"
readonly GNU_PLATFORM = "i686-darwin8" % "cpu-os" string for GNU
DarwinArch = "x86_64"

include("AMD64.common")
include("Darwin.common")

I've used full paths but you can use the environment path if you wish,
just make sure you're referencing the correct version.

**Comment by Clemens-H** [comment] 2016-05-20 19:58
I see.

Awesome, thanks!  I changed my config/AMD64_DARWIN to use the paths you just said.  I already have the MacPorts gcc installed.

Now it compiles!  I get a binary AMD64_DARWIN/prog.  When I run it, this happens:

>
$ AMD64_DARWIN/prog 
dyld: Library not loaded: @executable_path/../lib/libm3.5.dylib
  Referenced from: /Users/Clemens/Languages/Modula3/Hello/AMD64_DARWIN/prog
  Reason: image not found
Trace/BPT trap: 5


I have pkg/libm3/AMD64_DARWIN/libm3.5.dylib in my installation, of course.  There is still something wrong with my paths...

**Comment by Clemens-H** [comment] 2016-05-20 19:58
Hm, how can I get a statically linked binary?

**Comment by darko20** [comment] 2016-05-20 20:05
Put:

build_standalone()

in your m3makefile.

They're just standard dynamically loaded libraries so just google it for
the correct env var. I avoid them wherever possible myself.

**Comment by Clemens-H** [comment] 2016-05-20 20:26
Nice, thanks, I can run it with `DYLD_LIBRARY_PATH`.

Now my `m3makefile` looks like this:
>
import("libm3")
implementation("Hello")
build_standalone()
program("hello")

But `build_standalone()` doesn't seem to have any effect...

**Comment by darko20** [comment] 2016-05-20 20:29
It's putting all the libraries into the executable, so check its file size
to see if it's working. If you've fixed the path you won't notice any other
difference between the two.

**Comment by Clemens-H** [comment] 2016-05-20 20:30
Alright, I just deleted all output files and recompiled.  Now it produces a standalone binary.  Thanks again!

**Comment by jaykrell** [comment] 2016-05-21 00:23
What is our incompatibility with Apple gcc? I think I mainly use it -- er, it actually being clang now.

 - Jay

**Comment by Clemens-H** [comment] 2016-05-21 06:32
I believe using Apple gcc gives these error messages above:

>
Main.ms:2:9: error: unsupported directive '.stabs'
.stabs "Main.mc",100,0,0,Ltext0

Anyway, I got everything to work now with MacPorts gcc.

Btw, what's the easiest way to recompile cm3?  Where do I look for documentation?  I assume I have to specify the bootstrap compiler somewhere and then run a script.

**Comment by Clemens-H** [comment] 2016-05-21 11:40
I tried clang.  In config/AMD64_DARWIN, I put:
>
readonly SYSTEM_CC = "/usr/bin/clang"
readonly SYSTEM_LIBTOOL = "/usr/bin/libtool"
readonly SYSTEM_ASM = "/usr/bin/as"

But then there are undefined directives:
>
$ cm3
--- building in AMD64_DARWIN ---
>
new source -> compiling Hello.m3
"../src/Hello.m3", line 9: warning: potentially unhandled exception: IO.Error
1 warning encountered
Hello.ms:1:9: error: unsupported directive '.stabs'
        .stabs  "/Users/Clemens/Languages/Modula3/Hello/AMD64_DARWIN/",100,0,0,Ltext0
                ^
Hello.ms:2:9: error: unsupported directive '.stabs'
        .stabs  "Hello.mc",100,0,0,Ltext0
                ^
Hello.ms:5:9: error: unsupported directive '.stabs'
        .stabs  "gcc2_compiled.",60,0,0,0
                ^
Hello.ms:6:9: error: unsupported directive '.stabs'
        .stabs  "procedures_have_extra_block.",60,0,0,0
                ^
Hello.ms:7:9: error: unsupported directive '.stabs'
        .stabs  "m3_widechar_bitsize_16.",60,0,0,0
                ^
Hello.ms:11:2: error: unknown directive
        .stabd  46,0,0
        ^
Hello.ms:12:9: error: unsupported directive '.stabs'
        .stabs  "../src/Hello.m3",132,0,0,Ltext1
                ^
Hello.ms:14:2: error: unknown directive
        .stabd  68,0,7
        ^
Hello.ms:24:2: error: unknown directive
        .stabd  68,0,7
        ^
Hello.ms:29:2: error: unknown directive
        .stabd  68,0,8
        ^
Hello.ms:33:2: error: unknown directive
        .stabd  68,0,9
        ^
Hello.ms:41:2: error: unknown directive
        .stabd  68,0,10
        ^
Hello.ms:84:9: error: unsupported directive '.stabs'
        .stabs  "Hello_M3:F(0,1)=*(0,2)=(0,2)",36,0,7,_Hello_M3
                ^
Hello.ms:85:9: error: unsupported directive '.stabs'
        .stabs  "mode:p(0,3)=@s64;r(0,3);01000000000000000000000;0777777777777777777777;",160,0,0,-40
                ^
Hello.ms:86:2: error: unknown directive
        .stabn  192,0,0,LFBB1
        ^
Hello.ms:87:2: error: unknown directive
        .stabn  192,0,0,LBB2
        ^
Hello.ms:88:2: error: unknown directive
        .stabn  224,0,0,LBE2
        ^
Hello.ms:89:2: error: unknown directive
        .stabn  224,0,0,Lscope1
        ^
Hello.ms:91:9: error: unsupported directive '.stabs'
        .stabs  "",36,0,0,Lscope1-LFBB1
                ^
Hello.ms:92:2: error: unknown directive
        .stabd  78,0,0
        ^
Hello.ms:149:9: error: unsupported directive '.stabs'
        .stabs  "L_1:S(0,4)=s216;",38,0,0,_L_1
                ^
Hello.ms:150:9: error: unsupported directive '.stabs'
        .stabs  "MM_Hello:S(0,5)=s184;",38,0,0,_MM_Hello
                ^
Hello.ms:201:9: error: unsupported directive '.stabs'
        .stabs  "",100,0,0,Letext0
                ^
  assemble => 1
assembler failed assembling: Hello.ms
compilation failed => not building program "hello"
Fatal Error: package build failed

Everything works with MacPorts gcc, though.

**Comment by dragisha** [comment] 2016-05-21 12:47
It is supposed to work with MacPorts and not with clang.

**Comment by jaykrell** [comment] 2016-05-21 18:03
This is the assembler, but ok: "compiler driver".
Do any Mac debuggers understand stabs? If not, let's not ask for them. I thought I already had cm3cg not outputting stabs for Mac (macho).

 - Jay

**Comment by jaykrell** [comment] 2016-05-21 19:40
"It" should work more broadly. Apple, FSF, old, new. It is slightly more work to maintain and then easier for people to use.

 - Jay

**Comment by jaykrell** [comment] 2016-05-21 19:42
I'm short on time but this should be fixed. I recall no Mac debugger reads stabs & m3gdb doesn't support Mac, so should just not output them here, which I thought I was already avoiding.

 - Jay

**Comment by jaykrell** [comment] 2016-05-21 19:43
Scripts/python/update-all or full or such.

 - Jay

**Comment by Clemens-H** [comment] 2016-05-23 11:58
Yes, if this has been changed in the meantime, it would be great to have a new binary release for OS X.

**Comment by Clemens-H** [comment] 2016-05-29 11:55
I had some success with recompiling, but I am not sure if I did everything correctly and if it should this way.  I have the downloaded cm3 in `cm3-installed`, and I ran
>
PATH=/Users/Clemens/src/cm3-installed/bin:$PATH ./upgrade-full.sh

This recompiled everything successfully, it seems, and I could use the new cm3 to compile a hello-world program.

Then I became more ambitious and ran
>
CM3_INSTALL=/Users/Clemens/src/cm3-installed-1 PATH=/Users/Clemens/src/cm3-installed-0/bin:$PATH ./upgrade-full.sh

Here `cm3-installed-0` contains the original, bootstrap compiler and `cm3-installed-1` does not exist yet.

Again, recompilation succeeded:
>
[...]
do-cm3-all.py: Success.

But using the new compiler in `cm3-installed-1` does not work on my hello-world program:
>
$ ~/src/cm3-installed-1/bin/cm3 && AMD64_DARWIN/hello
--- building in AMD64_DARWIN ---
>
"/Users/Clemens/Languages/Modula3/Hello/src/m3makefile", line 1: quake runtime error: unable to open "/Users/Clemens/src/cm3-installed-1/pkg/libm3/AMD64_DARWIN/.M3EXPORTS" for reading
>
--procedure--  -line-  -file---
import             --  <builtin>
include_dir         1  /Users/Clemens/Languages/Modula3/Hello/src/m3makefile
                    4  /Users/Clemens/Languages/Modula3/Hello/AMD64_DARWIN/m3make.args
>
Fatal Error: package build failed

**Comment by jaykrell** [comment] 2016-05-29 22:44
Does the file exist that the error mentions? Probably not.


The scripts might have too in mind in-place build. A comprise, I realize. 
When it works, good. When it fails, needed a backup.

Make-dist.py is kinda what you want; it takes pains to seed the new build first by copying a bit from the old build, then in-place building, then doing it again to a third or so place.
 It puts everything into "temp" and leaves the user to copy or extract the output to where they want.


 - Jay

**Comment by RodneyBates** [comment] 2016-05-29 23:22
On 05/29/2016 06:55 AM, Clemens Heitzinger wrote:
> I had some success with recompiling, but I am not sure if I did everything correctly and if it should this way. I have the downloaded cm3 in |cm3-installed|, and I ran
>
>     PATH=/Users/Clemens/src/cm3-installed/bin:$PATH ./upgrade-full.sh
>
> This recompiled everything successfully, it seems, and I could use the new cm3 to compile a hello-world program.
>
> Then I became more ambitious and ran
>
>     CM3_INSTALL=/Users/Clemens/src/cm3-installed-1 PATH=/Users/Clemens/src/cm3-installed-0/bin:$PATH ./upgrade-full.sh
>
> Here |cm3-installed-0| contains the original, bootstrap compiler and |cm3-installed-1| does not exist yet.
>
> Again, recompilation succeeded:
>
>     [...]
>     do-cm3-all.py: Success.
>
> But using the new compiler in |cm3-installed-1| does not work on my hello-world program:
>
>     $ ~/src/cm3-installed-1/bin/cm3 && AMD64_DARWIN/hello
>     --- building in AMD64_DARWIN ---
>
>     "/Users/Clemens/Languages/Modula3/Hello/src/m3makefile", line 1: quake runtime error: unable to open "/Users/Clemens/src/cm3-installed-1/pkg/libm3/AMD64_DARWIN/.M3EXPORTS" for reading
>

/Users/Clemens/src/cm3-installed-1/pkg/libm3/AMD64_DARWIN should contain copies of
.M3EXPORTS, .M3WEB, libm3.a, libm3.m3x, a symlink to libm3.so, and all
the *.[im]3 files from <build_directory>/cm3/m3-libs/libm3/AMD64_DARWIN
.

Don't know why it didn't happen, but that's what is needed.

Similarly for additional libraries your program needs.

**Comment by Clemens-H** [comment] 2016-05-30 15:00
Thanks.  I ran
>
STAGE=~/src/cm3-dist-0 ./make-dist.sh

It produced a compiler `$STAGE/cm3/bin/cm3`, which works beautifully.

**Comment by jaykrell** [comment] 2016-05-30 19:44
I meant make-dist.py.

 - Jay

**Comment by Clemens-H** [comment] 2016-05-30 21:03
I see, I ran it like this now:
>
time PATH=/Users/Clemens/src/cm3-installed-0/bin:$PATH ./make-dist.py

The resulting tar file contains a nicely working compiler.

**Comment by jaykrell** [comment] 2016-05-31 00:28
This is what I use to make releases. You make one? :)

You see it makes two varieties like "min" and "all". "Min" is enough to build compiler and some other programs, "all" is everything we have (including "min" -- inclusive not additive.) It is sloppy but convenient.

 - Jay

**Comment by Clemens-H** [comment] 2016-05-31 15:28
Yes, I saw the min and all tar.gz files yesterday.  I extracted the "all" tar file and the compiler worked fine.  (The tar.gz files are gone from my /var directory now.)

I'd be happy to help with a release.  What should I do?

**Comment by FranklinChen** [comment] 2019-02-23 06:30
Any more on this?

**Comment by FranklinChen** [comment] 2021-02-24 21:00
Ha, I'm back almost exactly two years later, and see a  new release for Mac on ARM, but not on x86_64...

**Comment by jaykrell** [comment] 2021-02-24 21:05
No problem, I’ll make one tonight.

**Comment by jaykrell** [comment] 2021-02-24 21:06
But it did sound like you made one for yourself. Anyway I’ll try to remember later.

**Comment by jaykrell** [comment] 2021-02-26 09:56
The Mac I'm at won't build 32bit, so I did AMD64 only.
Please try https://github.com/modula3/cm3/releases/tag/AMD64_DARWIN-20210226

I expect there will be one very fatal problem.
It will try to run cm3cg and it isn't there.
If so, please add https://github.com/modula3/cm3/releases/tag/AMD64_DARWIN-20210226 to bin/cm3.cfg.

**Comment by coder5506** [comment] 2021-12-22 13:49
Not quite 6-years late, I know, but I've spent the better part of the past 4-months getting the macOS distribution in shape and I think it is ready for general use.  For anybody still following this issue, please try the latest [macOS release](https://github.com/modula3/cm3/wiki/Getting-Started:-macOS).  I'll be closing this and the other lingering Mac-related reports from the 19th century, but please open new issues if there are problems with the latest.

**Closed by coder5506** 2021-12-22 13:49 UTC
