### ISSUE TITLE
Variable initialization

### ISSUE THREAD

**Issue by jcchu** [modula3/cm3#44] opened 2019-02-08 07:33 UTC
The language definition says initial values in variable declarations are a shorthand for assignments inserted “at the beginning of the executable part of the block” “in the order they are declared”.

The following declarations don’t achieve the expected result.

    VAR
      x1 := y1 + 3;
      y1 := -1;
      x2 := y2 + 3;
      y2 := TRUNC(cos(Pi));
  
At the beginning of the block, `x2` will be 3 as expected, but `x1` will have value 2.

**Comment by mikanystrom** [comment] 2019-02-08 16:46
I think that's an allowable result. y1 is being accessed before it's
initialized, and the language spec says it can have any value of its type.
It just happens to be -1, then.. am I misreading the code?

    Mika

**Comment by jcchu** [comment] 2019-02-09 02:12
> and the language spec says it can have any value of its type

But only if its declaration didn’t specify an initial value, no?

— JC

**Comment by mikanystrom** [comment] 2019-02-09 02:25
Hmmmm? what are you saying?  I read the spec as saying, first, your code is
equivalent to:

VAR
  x1 : INTEGER;
  y1 : INTEGER;
  x2 : INTEGER;
  y2 : INTEGER;
BEGIN
  x1 := y1 + 3; (* y1 not initialized *)
  y1 := -1;
  x2 := y2 + 3; (* y2 not initialized *)
  y2 := TRUNC(cos(Pi)); (* = -1 *)

since neither y1 nor y2 is initialized before it's used, the system is
allowed to put any value of INTEGER in those variables.  If you are
observing x2=3 and x1=2, that means it "happened to choose" the
initializations y1=-1 and y2=0...right??

    Mika

**Comment by mikanystrom** [comment] 2019-02-09 02:34
Oh I see what you are saying.  The first and second paragraphs of 2.4.3 are
slightly contradictory.

"VAR id : T := E

declares id as a variable of type T *whose initial value is the value of E*.
...
The initial value is a shorthand that is equivalent to inserting the
assignment id := E at the beginning of the executable part of the block.  *If
several variables have initial values, their assignments are inserted in
the order they are declared*."

In your example, VAR x1 := y1 + 3; y1 := -1; the first paragraph
says---ahem, suggests---that y1's initial value is -1, whereas the second
says it is arbitrary.

the problem maybe can be resolved by saying that the second para. defines
the meaning of "the value of E".

Maybe it's the fact fact that the term "initial value" isn't 100% clearly
defined.  I think the first para is a bit wrong...not what the authors
intended, actually.

     Mika

**Comment by jcchu** [comment] 2019-02-09 02:37
Right, I see your point now.  Should’ve read the “for example” paragraph below.  :(

It’s still a bit awkward though, although I can’t blame the compiler for violating the language definition.

— JC

**Comment by jcchu** [comment] 2019-02-09 02:46
> The first and second paragraphs of 2.4.3 are slightly contradictory.

The second paragraph actually elaborated on the meaning of “VAR v1 := e1; v2 := e2;” and my example is equivalent to the following code as you suggested.

    VAR
      x1, y1, x2, y2: INTEGER;
    BEGIN
      x1 := y1 + 3; (* y1 not initialized *)
      y1 := -1;
      x2 := y2 + 3; (* y2 not initialized *)
      y2 := TRUNC(cos(Pi)); (* = -1 *)
    END

So the result is a bit surprising, but doesn’t seem to violate the language definition.

— JC

**Comment by mikanystrom** [comment] 2019-02-09 03:28
Yeah ... you're right, that was what I thought first.  But the first
paragraph also says that y2's "initial value" is -1.  It's kind of strange,
then, that y2's value when "x2 := y2 + 3" is evaluated is zero!  That is,
y2 has a value before it takes on its "initial value" that is different
from its "initial value".

I think the spec is ... uncharacteristically for the Green Book ... poorly
written here.

**Comment by jcchu** [comment] 2019-02-09 04:23
> That is, y2 has a value before it takes on its "initial value" that is different from its "initial value".

Hmm, the way I see it now is that the presence of an “initial value” (expression) is supposed to be “equivalent to” an assignment (of that expression to the variable); a variable’s value _before_ the assignment (if any) is supposed to be arbitrary.  So a variable’s value at the beginning a block—which is _not_ called its “initial value”—indeed may not be equal to its “initial value” (expression) evaluated there once more (unless of course its “initial value” (expression) is constant).

— JC

**Comment by mikanystrom** [comment] 2019-02-09 19:18
No I agree with you, that's definitely what was implemented and I think
it's also what was intended.  But I think the Green Book doesn't say that
with 100% clarity in 2.4.3.  You're not supposed to have to rely on the
example to derive the exact meaning of a section.

**Closed** 2019-02-19 12:22 UTC
